apiVersion: apps/v1
kind: Deployment
metadata:
  name: geypet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geypet
  template:
    metadata:
      labels:
        app: geypet
    spec:
      containers:
      - image: okteto.dev/geypet:latest
        name: geypet
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "f981e732-1efe-4587-9151-67f6b6780615"
        - name: Vless_Path
          value: "/jkduij897"
        - name: Vmess_UUID
          value: "f981e732-1efe-4587-9151-67f6b6780615"
        - name: Vmess_Path
          value: "/uiytre345"
        - name: Share_Path
          value: "/v2link"
